#!/usr/bin/env python3
"""
Rebuild the consolidated skills library from configured inputs into:

    skills/<category>/<unit>/            one dir per skill unit (composites intact)
    agents/  commands/  standards/  templates/  docs/  tools/
    skills-index.json                    machine-readable catalog
    CONSOLIDATION.md                     per-decision log (kept/skipped/why)
    MAINTAINERS.md                       provenance: source ids, pins, licenses
                                         (the ONLY file that names input repos;
                                         the pinned-sources block between the
                                         markers is regenerated by this script)

Inputs are identified everywhere else by opaque ids (s1..s4, local).
`local-skills/<category>/<name>/` holds library-authored skills and always
survives rebuilds.

Dedup rules:
  R1  Same unit name, SKILL.md byte-identical  -> keep one copy.
  R2  Stale/expanded forks of an original author's skill -> keep the original
      author's current version.
  R3  Same name but genuinely different skills -> keep both in different
      categories; collision recorded in the index.
  R4  Sub-skills of different composites sharing names -> no conflict:
      composites are kept as single units.

Run:  python3 tools/consolidate.py   (from the repo root)
"""

import hashlib
import json
import os
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOME = Path.home()
OUT_SKILLS = ROOT / "skills"
LOCAL_SRC = ROOT / "local-skills"

# Source paths (see MAINTAINERS.md for what each id is; override via env)
SRC = {
    "s1": Path(os.getenv("SRC_S1", str(HOME / ".claude" / "claude-skills"))),
    "s2": Path(os.getenv("SRC_S2", str(HOME / ".claude" / "mattpocock-skills"))),
    "s3": Path(os.getenv("SRC_S3", str(HOME / ".claude" / "superpowers"))),
    "s4": Path(os.getenv("SRC_S4", str(HOME / ".claude" / "anthropic-skills"))),
}

# Flat `skills/<name>/` sources; s4 include-list is the permissively-licensed
# subset only (its document-processing skills are source-available, NOT open
# source -> never ingest them). Rationale: docs/ECOSYSTEM.md; ids: MAINTAINERS.md.
EXTRA_SOURCES = [
    {"source": "s3", "category": "methodology", "include": None},
    {"source": "s4", "category": "engineering",
     "include": {"skill-creator", "mcp-builder", "webapp-testing", "claude-api", "frontend-design"}},
]

S1_CATEGORY_MAP = {
    "engineering": "engineering",
    "engineering-team": "engineering",
    "product-team": "product",
    "research": "research",
    "research-ops": "research-ops",
    "project-management": "project-management",
    "productivity": "productivity",
    "business-growth": "business",
    "business-operations": "business",
    "commercial": "business",
    "marketing-skill": "marketing",
    "marketing": "marketing",
    "finance": "finance",
    "compliance-os": "compliance",
    "c-level-advisor": "c-level",
    "ra-qm-team": "ra-qm",
    "markdown-html": "documents",
    "loop-library": "engineering",
}
S2_CATEGORY_MAP = {"engineering": "workflow", "productivity": "productivity", "misc": "misc"}
S2_SKIP_DIRS = {"deprecated", "in-progress", "personal"}

# R2: s1 units that are stale/expanded forks of s2 originals -> skip
S1_STALE_FORKS = {"grill-me", "grill-with-docs"}
S1_SKIP_UNIT_PATHS = {"engineering/handoff", "productivity/handoff"}
# Upstream test fixtures, not real skills
FIXTURE_UNITS = {"sample-skill"}
# Meta-skills only meaningful inside their home plugin -> excluded
HOME_PLUGIN_META = {"using-superpowers"}
# Neutral renames (applied to unit dirs, frontmatter names, and all cross-references)
RENAMES = {
    "setup-matt-pocock-skills": "setup-workflow-skills",
    "ask-matt": "which-skill",
}

ORIGINAL_AUTHOR_ORDER = {"local": 0, "s2": 1, "s3": 2, "s4": 3, "s1": 4}


def fm(text):
    m = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    name = desc = ""
    if m:
        for line in m.group(1).splitlines():
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip().strip("\"'")
            elif line.startswith("description:"):
                desc = line.split(":", 1)[1].strip().strip("\"'")
    return name, desc


def unit_for(skill_md: Path, vendor_root: Path):
    """Return (unit_root, unit_name) for an s1 SKILL.md path."""
    rel = skill_md.relative_to(vendor_root)
    parts = rel.parts
    if len(parts) >= 4 and parts[-3] == "skills" and len(parts) == 4:
        return vendor_root / parts[0] / "skills" / parts[2], parts[2]
    if len(parts) >= 5 and parts[-3] == "skills":
        return vendor_root / parts[0] / parts[1], parts[1]
    if len(parts) == 3:
        return vendor_root / parts[0] / parts[1], parts[1]
    return skill_md.parent, skill_md.parent.name


def collect_units():
    units = {}  # str(unit_root) -> dict

    def add(smd, unit_root, name, source, src_root, category):
        u = units.setdefault(str(unit_root), {
            "root": unit_root, "src_root": src_root, "name": name,
            "source": source, "category": category, "skill_mds": [],
        })
        u["skill_mds"].append(smd)

    if LOCAL_SRC.exists():
        for smd in sorted(LOCAL_SRC.rglob("SKILL.md")):
            rel = smd.relative_to(LOCAL_SRC)
            category = rel.parts[0] if len(rel.parts) > 2 else "misc"
            add(smd, smd.parent, smd.parent.name, "local", LOCAL_SRC, category)

    for smd in sorted(SRC["s1"].rglob("SKILL.md")):
        if any(p.startswith(".") for p in smd.relative_to(SRC["s1"]).parts):
            continue  # platform mirrors (.gemini/.hermes/...)
        rel0 = smd.relative_to(SRC["s1"]).parts[0]
        if rel0 not in S1_CATEGORY_MAP:
            continue
        unit_root, unit_name = unit_for(smd, SRC["s1"])
        add(smd, unit_root, unit_name, "s1", SRC["s1"], S1_CATEGORY_MAP[rel0])

    base2 = SRC["s2"] / "skills"
    for smd in sorted(base2.rglob("SKILL.md")):
        rel0 = smd.relative_to(base2).parts[0]
        if rel0 in S2_SKIP_DIRS:
            continue
        add(smd, smd.parent, smd.parent.name, "s2", SRC["s2"],
            S2_CATEGORY_MAP.get(rel0, "misc"))

    for ex in EXTRA_SOURCES:
        base = SRC[ex["source"]] / "skills"
        if not base.exists():
            print(f"WARNING: source {ex['source']} missing, skipped: {base}")
            continue
        for smd in sorted(base.rglob("SKILL.md")):
            top = smd.relative_to(base).parts[0]
            if ex["include"] is not None and top not in ex["include"]:
                continue
            add(smd, base / top, top, ex["source"], SRC[ex["source"]], ex["category"])
    return list(units.values())


def write_pins():
    """Regenerate the pinned-sources block inside MAINTAINERS.md."""
    mfile = ROOT / "MAINTAINERS.md"
    if not mfile.exists():
        print("WARNING: MAINTAINERS.md missing — pins not written")
        return
    lock = {}
    for sid, root in SRC.items():
        try:
            sha = subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"],
                                 capture_output=True, text=True, check=True).stdout.strip()
            origin = subprocess.run(["git", "-C", str(root), "remote", "get-url", "origin"],
                                    capture_output=True, text=True, check=True).stdout.strip()
        except Exception:
            sha, origin = "unknown", "unknown"
        lock[sid] = {"origin": origin, "commit": sha}
    block = "```json\n" + json.dumps(lock, indent=2) + "\n```"
    content = mfile.read_text()
    new = re.sub(r"(<!-- PINS:BEGIN -->).*?(<!-- PINS:END -->)",
                 rf"\1\n{block}\n\2", content, flags=re.S)
    mfile.write_text(new)


def main():
    if OUT_SKILLS.exists():
        shutil.rmtree(OUT_SKILLS)
    units = collect_units()
    log, index, taken = [], [], {}
    units.sort(key=lambda u: (ORIGINAL_AUTHOR_ORDER.get(u["source"], 9), u["name"]))

    for u in units:
        rel_unit = f'{u["source"]}/{u["root"].relative_to(u["src_root"])}'
        src_rel = str(u["root"].relative_to(u["src_root"]))
        name, cat, src = u["name"], u["category"], u["source"]
        if name in RENAMES:
            log.append(f"- RENAME `{rel_unit}` -> `{cat}/{RENAMES[name]}` — neutral naming policy")
            name = RENAMES[name]

        if name in FIXTURE_UNITS:
            log.append(f"- SKIP `{rel_unit}` — upstream test fixture, not a skill")
            continue
        if name in HOME_PLUGIN_META:
            log.append(f"- SKIP `{rel_unit}` — meta-skill tied to its home plugin, no value standalone")
            continue
        if src == "s1" and (name in S1_STALE_FORKS or src_rel in S1_SKIP_UNIT_PATHS):
            log.append(f"- SKIP `{rel_unit}` — stale/expanded fork; the original author's current version is kept (R2)")
            continue

        skipped_r1 = False
        for (ocat, oname), other in taken.items():
            if oname != name:
                continue
            mine = u["skill_mds"][0].read_text(errors="replace")
            theirs = other["skill_mds"][0].read_text(errors="replace")
            if hashlib.md5(mine.encode()).hexdigest() == hashlib.md5(theirs.encode()).hexdigest():
                log.append(f"- SKIP `{rel_unit}` — byte-identical to kept `{ocat}/{name}` (R1)")
                skipped_r1 = True
                break
        if skipped_r1:
            continue

        dest = OUT_SKILLS / cat / name
        if dest.exists():
            log.append(f"- SKIP `{rel_unit}` — name collision with already-kept `{cat}/{name}` (first-kept wins; review manually)")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(u["root"], dest)
        prior = [k for k in taken if k[1] == name]
        if prior:
            log.append(f"- KEEP BOTH `{cat}/{name}` and `{prior[0][0]}/{name}` — same name, different skills (R3)")
        taken[(cat, name)] = u
        n, d = fm(u["skill_mds"][0].read_text(errors="replace"))
        for old, new in RENAMES.items():
            n, d = n.replace(old, new), d.replace(old, new)
        index.append({
            "name": n or name, "category": cat, "path": f"skills/{cat}/{name}",
            "source": src, "description": d,
            "composite": len(u["skill_mds"]) > 1, "sub_skills": len(u["skill_mds"]),
            "has_scripts": bool(list(dest.rglob("scripts"))),
        })

    # non-skill assets from s1
    for src_dir, dst in (("agents", "agents"), ("commands", "commands"),
                         ("standards", "standards"), ("templates", "templates")):
        s = SRC["s1"] / src_dir
        if s.exists():
            d = ROOT / dst
            if d.exists():
                shutil.rmtree(d)
            shutil.copytree(s, d)
    docs = ROOT / "docs"
    docs.mkdir(exist_ok=True)
    for f in ("SKILL-AUTHORING-STANDARD.md", "CONVENTIONS.md"):
        if (SRC["s1"] / f).exists():
            shutil.copy2(SRC["s1"] / f, docs / f)
    lic = ROOT / "LICENSES"
    if lic.exists():
        shutil.rmtree(lic)
    lic.mkdir()
    for sid in ("s1", "s2", "s3"):
        src_lic = SRC[sid] / "LICENSE"
        if src_lic.exists():
            shutil.copy2(src_lic, lic / f"LICENSE-{sid}")
    # s4 skills carry per-skill LICENSE.txt, retained by copytree

    # rewrite renamed skill references across all copied markdown
    for md in OUT_SKILLS.rglob("*.md"):
        text = md.read_text(errors="replace")
        new_text = text
        for old, new in RENAMES.items():
            new_text = new_text.replace(old, new)
        if new_text != text:
            md.write_text(new_text)

    write_pins()

    index.sort(key=lambda e: (e["category"], e["name"]))
    (ROOT / "skills-index.json").write_text(json.dumps(index, indent=2) + "\n")

    header = (
        "# Consolidation log\n\n"
        f"Units kept: **{len(index)}** · decisions below. Rules: R1 byte-identical dedup · "
        "R2 stale/expanded forks dropped in favor of the original author's current version · "
        "R3 same-name different-skill kept in separate categories · R4 composite units kept "
        "intact (sub-skill name overlap is not a conflict).\n\n"
        "Input ids (s1..s4, local) are resolved in `MAINTAINERS.md` (maintainers-only "
        "provenance file). One input's `deprecated/`, `in-progress/`, `personal/` dirs are "
        "excluded by policy.\n\n## Decisions\n\n"
    )
    (ROOT / "CONSOLIDATION.md").write_text(header + "\n".join(sorted(set(log))) + "\n")
    print(f"kept units: {len(index)}; logged decisions: {len(set(log))}")
    print(f"categories: {sorted({e['category'] for e in index})}")


if __name__ == "__main__":
    main()
